{
  cpu: '1024',
  memory: '2048',
  container_def_name: 'dev-pocopark-user-api',
  image: '020604330519.dkr.ecr.ap-northeast-1.amazonaws.com/dev-api',
  secrets: {
    MYSQL_POCOPARK_HOST: '/dev/aurora/main/writer_host',
    MYSQL_POCOPARK_PASSWORD: '/dev/aurora/main/pocopark_password',
    MYSQL_POCOPARK_USER: '/dev/aurora/main/pocopark_user',
    JWT_SECRET_KEY: '/dev/ecs/api/jwt_secret_key',
    OPENSEARCH_AWS_ACCESS_KEY_ID: '/dev/opensearch/access_key_id',
    OPENSEARCH_AWS_SECRET_ACCESS_KEY: '/dev/opensearch/secret_access_key',
    OPENSEARCH_ENDPOINT: '/dev/opensearch/endpoint',
    ADMIN_BASIC_AUTH_USER: '/dev/ecs/api/admin_basic_auth_user',
    ADMIN_BASIC_AUTH_PASSWORD: '/dev/ecs/api/admin_basic_auth_password',
    POCOAUTH_CLIENT_ID: '/dev/ecs/api/pocoauth_client_id',
    POCOAUTH_CLIENT_SECRET: '/dev/ecs/api/pocoauth_client_secret',
    MICROCMS_API_KEY: '/dev/ecs/api/microcms_api_key',
    MICROCMS_SIGNATURE_SECRET: '/dev/ecs/api/microcms_signature_secret',
    SLACK_WEBHOOK_URL: '/dev/ecs/api/slack_webhook_url',
    SECRET_KEY_BASE: '/dev/ecs/api/SECRET_KEY_BASE',
    DATADOG_API_KEY: '/dev/ecs/api/DATADOG_API_KEY',
  },
  environments: {
    PORT: '3000',
    HOST: 'api.dev.pocopark.pococha.com',
    COOKIE_DOMAIN: 'dev.pocopark.pococha.com',
    ALLOW_CORS_ORIGINS: 'https://dev.pocopark.pococha.com,http://localhost:3333',
    RAILS_ENV: 'production',
    RAILS_LOG_TO_STDOUT: 'true',
    QA_MODE: '1',
    MICROCMS_DOMAIN: "pocopark-yzfqar7hwr68xx10e7ki",
    POCOAUTH_SERVER: 'https://account-protodev0122.dev.pococha.com',
    POCOAUTH_REDIRECT_URI: 'https://dev.pocopark.pococha.com/callback',
    POCOAUTH_STATE: 'pocopark-dev',
    ADMIN_SERVICE_ORIGIN: 'https://admin.dev.pocopark.pococha.com',
    SKIP_ALLOWED_CHECK: 'true',
    APP_STAGE: 'dev',
    # timecopを正しく動かすために必要
    WEB_CONCURRENCY: '1',
    USER_WEB_URL: 'https://dev.pocopark.pococha.com',
    MANAGEMENT_USER_BASIC_AUTH_USERNAME: "luna-dev",
    MANAGEMENT_USER_BASIC_AUTH_PASSWORD: "tayunama",
  },
}
