// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameClinicalCaseAttendingDoctor = "clinical_case_attending_doctors"

// ClinicalCaseAttendingDoctor mapped from table <clinical_case_attending_doctors>
type ClinicalCaseAttendingDoctor struct {
	ID                string    `gorm:"column:id;primaryKey" json:"id"`
	ClinicalCaseID    string    `gorm:"column:clinical_case_id;not null" json:"clinical_case_id"`
	AttendingDoctorID string    `gorm:"column:attending_doctor_id;not null" json:"attending_doctor_id"`
	CreatedAt         time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt         time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName ClinicalCaseAttendingDoctor's table name
func (*ClinicalCaseAttendingDoctor) TableName() string {
	return TableNameClinicalCaseAttendingDoctor
}
