// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameClinicalCasePatient = "clinical_case_patients"

// ClinicalCasePatient mapped from table <clinical_case_patients>
type ClinicalCasePatient struct {
	ID             string    `gorm:"column:id;primaryKey" json:"id"`
	ClinicalCaseID string    `gorm:"column:clinical_case_id;not null" json:"clinical_case_id"`
	PatientID      string    `gorm:"column:patient_id;not null" json:"patient_id"`
	CreatedAt      time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName ClinicalCasePatient's table name
func (*ClinicalCasePatient) TableName() string {
	return TableNameClinicalCasePatient
}
