// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameClinicalCaseDetail = "clinical_case_details"

// ClinicalCaseDetail mapped from table <clinical_case_details>
type ClinicalCaseDetail struct {
	ID             string    `gorm:"column:id;primaryKey" json:"id"`
	ClinicalCaseID string    `gorm:"column:clinical_case_id;not null" json:"clinical_case_id"`
	Name           string    `gorm:"column:name;not null" json:"name"`
	Contact        string    `gorm:"column:contact;not null" json:"contact"`
	CreatedAt      time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName ClinicalCaseDetail's table name
func (*ClinicalCaseDetail) TableName() string {
	return TableNameClinicalCaseDetail
}
