// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameClinicDetail = "clinic_details"

// ClinicDetail mapped from table <clinic_details>
type ClinicDetail struct {
	ID        string    `gorm:"column:id;primaryKey" json:"id"`
	ClinicID  string    `gorm:"column:clinic_id;not null" json:"clinic_id"`
	Name      string    `gorm:"column:name;not null" json:"name"`
	NameKana  string    `gorm:"column:name_kana;not null" json:"name_kana"`
	Contact   string    `gorm:"column:contact;not null" json:"contact"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName ClinicDetail's table name
func (*ClinicDetail) TableName() string {
	return TableNameClinicDetail
}
