// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameClinicalCase = "clinical_cases"

// ClinicalCase mapped from table <clinical_cases>
type ClinicalCase struct {
	ID              string                      `gorm:"column:id;primaryKey" json:"id"`
	CreatedAt       time.Time                   `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       time.Time                   `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	AttendingDoctor ClinicalCaseAttendingDoctor `gorm:"foreignKey:clinical_case_attending_doctors" json:"attending_doctor"`
	Patient         ClinicalCasePatient         `gorm:"foreignKey:clinical_case_patients" json:"patient"`
}

// TableName ClinicalCase's table name
func (*ClinicalCase) TableName() string {
	return TableNameClinicalCase
}
