// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameOrganization = "organizations"

// Organization mapped from table <organizations>
type Organization struct {
	ID                 string                `gorm:"column:id;primaryKey" json:"id" validate:"required,ulid"`
	CreatedAt          time.Time             `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt          time.Time             `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	OrganizationDetail OrganizationDetail    `json:"organization_detail"`
	PartOf             *PartOfOrganization   `json:"part_of"`
	Active             *ActiveOrganization   `json:"active"`
	Cancel             *CanceledOrganization `json:"cancel"`
}

// TableName Organization's table name
func (*Organization) TableName() string {
	return TableNameOrganization
}
