// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameOrganizationDetail = "organization_details"

// OrganizationDetail mapped from table <organization_details>
type OrganizationDetail struct {
	OrganizationID   string    `gorm:"column:organization_id;primaryKey" json:"organization_id"`
	Name             string    `gorm:"column:name;not null" json:"name" validate:"required"`
	Alias            string    `gorm:"column:alias;not null" json:"alias"`
	OrganizationType int32     `gorm:"column:organization_type;not null" json:"organization_type"`
	Contact          string    `gorm:"column:contact;not null" json:"contact" validate:"required,email"`
	Description      string    `gorm:"column:description;not null" json:"description"`
	CreatedAt        time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName OrganizationDetail's table name
func (*OrganizationDetail) TableName() string {
	return TableNameOrganizationDetail
}
