// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNamePartOfOrganization = "part_of_organizations"

// PartOfOrganization mapped from table <part_of_organizations>
type PartOfOrganization struct {
	OrganizationID       string    `gorm:"column:organization_id;primaryKey" json:"organization_id"`
	PartOfOrganizationID string    `gorm:"column:part_of_organization_id;primaryKey" json:"part_of_organization_id"`
	CreatedAt            time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt            time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName PartOfOrganization's table name
func (*PartOfOrganization) TableName() string {
	return TableNamePartOfOrganization
}
