run:
  timeout: 5m
  skip-dirs:
    - api
    - cmd

issues:
  exclude-use-default: false

  exclude-rules:
    - source: "defer"
      linters:
        - errcheck

  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - stylecheck
    - misspell
    - thelper
    - gosimple
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - durationcheck
    - errorlint
    - exhaustive
    - goimports
    - gosec
    - noctx
    - paralleltest
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    - revive

linters-settings:
  gosimple:
    go: "1.20"
    checks:
      - "all"
  staticcheck:
    go: "1.20"
    checks:
      - "all"
  stylecheck:
    go: "1.20"
    checks:
      - "all"
      - "-ST1000"
  revive:
    ignore-generated-header: false
    severity: error
    rules:
      - name: exported
        arguments: ["checkPrivateReceivers", "sayRepetitiveInsteadOfStutters"]
      - name: if-return

  unused:
    go: "1.20"
