{
  cpu: '512',
  container_def_name: 'dev-yourapp-migration',
  memory: '1024',
  image: '020604330519.dkr.ecr.ap-northeast-1.amazonaws.com/dev-api',
  command: [
    'bundle',
    'exec',
    'rails',
    'opensearch:destroy',
    'opensearch:migrate',
    'db:migrate:reset',
    'badge:seed',
    'db:seed',
  ],
  secrets: {
    MYSQL_YOURAPP_HOST: '/dev/aurora/main/writer_host',
    MYSQL_YOURAPP_PASSWORD: '/dev/aurora/main/YOURAPP_password',
    MYSQL_YOURAPP_USER: '/dev/aurora/main/YOURAPP_user',
    MYSQL_YOURAPP_TEST_HOST: '/dev/aurora/main/writer_host',
    MYSQL_YOURAPP_TEST_PASSWORD: '/dev/aurora/main/master_password',
    MYSQL_YOURAPP_TEST_USER: '/dev/aurora/main/master_user',
    OPENSEARCH_AWS_ACCESS_KEY_ID: '/dev/opensearch/access_key_id',
    OPENSEARCH_AWS_SECRET_ACCESS_KEY: '/dev/opensearch/secret_access_key',
    OPENSEARCH_ENDPOINT: '/dev/opensearch/endpoint',
    AWS_ACCESS_KEY_ID: '/dev/ecs/s3_access_key',
    AWS_SECRET_ACCESS_KEY: '/dev/ecs/s3_secret_key',
    DATADOG_API_KEY: '/dev/ecs/api/DATADOG_API_KEY',
  },
  environments: {
    PORT: '3000',
    HOST: 'yourapp.ispec.app',
    RAILS_ENV: 'production',
    DISABLE_DATABASE_ENVIRONMENT_CHECK: '1',
    QA_MODE: '1',
  },
}
