name: Upload Release Cli

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release Packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Compile
        working-directory: cli
        run: |
          deno compile -A --output starry index.ts --target ${{ matrix.target }}

      - name: Release
        working-directory: cli
        run: |
          export VERSION="0.1.0"
          curl -L "https://github.com/tcnksm/ghr/releases/download/${GHR_VERSION}/ghr_${GHR_VERSION}_linux_amd64.tar.gz" | tar xvz
          "ghr_${GHR_VERSION}_linux_amd64/ghr" -u ispec-inc -r starry -replace -n "$VERSION" "$VERSION" starry-${{ matrix.target }}
        env:
          GHR_VERSION: v0.13.0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
