name: Upload Release Cli

on:
  push:
    tags:
      - "v[0-9]+\\.[0-9]+\\.[0-9]+"

jobs:
  compile:
    name: Release Packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Compile
        working-directory: cli
        run: |
          deno compile -A --output starry-${{ matrix.target }} --target ${{ matrix.target }} index.ts

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: starry-${{ matrix.target }}
          path: cli/starry-${{ matrix.target }}


  release:
    name: Release Packages
    runs-on: ubuntu-latest
    needs:
      - compile
    steps:
      - uses: actions/checkout@v3

      - { uses: actions/download-artifact@v3, with: { name: starry-x86_64-unknown-linux-gnu,  path: starry/ } }
      - { uses: actions/download-artifact@v3, with: { name: starry-x86_64-apple-darwin,       path: starry/ } }
      - { uses: actions/download-artifact@v3, with: { name: starry-aarch64-apple-darwin,      path: starry/ } }

      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_COMPRESS: xz
          GHR_REPLACE: true
          GHR_PATH: starry/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
